In [1]:
%matplotlib inline

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
n_1 = float(input("n1: \n"))

In [26]:
n_2 = float(input("n2: \n"))

n2: 
1.5


In [22]:
r = float(input("r: \n"))

r: 
50


In [23]:
t = float(input("t: \n"))

t: 
1


In [42]:
R = np.array(
    [[1, 0],
    [(-(n_2-n_1)/r), 1],
])

T = np.array([
    [1, t/n_2],
    [0, 1],
])

R, T

(array([[ 1.  ,  0.  ],
        [-0.01,  1.  ]]),
 array([[1.        , 0.66666667],
        [0.        , 1.        ]]))

In [43]:
M=np.dot(T, R)
M

array([[ 0.99333333,  0.66666667],
       [-0.01      ,  1.        ]])

# New Task
<hr>


In [3]:
t = float(input())

1


In [4]:
r1 = float(input())

50


In [5]:
r2 = float(input())

-50


In [6]:
n1 = float(input())

1


In [7]:
n2 = float(input())

1.5


In [8]:
n3 = float(input())

1


In [9]:
R1 = np.array([
    [1, 0],
    [-(n2-n1)/r1, 1],
])

T = np.array([
    [1, t/n2],
    [0, 1],
])

R2 = np.array([
    [1, 0],
    [-(n3-n2)/r2, 1],
])

print(f"R1: \n{R1}")
print(f"T: \n{T}")
print(f"R2: \n{R2}")

R1: 
[[ 1.    0.  ]
 [-0.01  1.  ]]
T: 
[[1.         0.66666667]
 [0.         1.        ]]
R2: 
[[ 1.    0.  ]
 [-0.01  1.  ]]


In [10]:
# M = np.dot(R2, T)
# M = np.dot(M, R1)
# M

M = np.dot(T, R1)
M = np.dot(R2, M)
M


array([[ 0.99333333,  0.66666667],
       [-0.01993333,  0.99333333]])

In [11]:
M = np.dot(R2, T)
M = np.dot(M, R1)
M

array([[ 0.99333333,  0.66666667],
       [-0.01993333,  0.99333333]])

# New Task
<hr>

In [12]:
r1 = float(input())

50


In [13]:
r2 = float(input())

-50


In [14]:
r3 = float(input())

25


In [15]:
r4 = float(input())

-25


In [16]:
t1 = float(input())

1


In [17]:
t2 = float(input())

1


In [18]:
d = float(input())

75


In [19]:
n1 = float(input())

1


In [20]:
n2 = float(input())

1.5


In [21]:
n3 = float(input())

1


In [22]:
n4 = float(input())

1.5


In [23]:
n5 = float(input())

1


In [24]:
R1 = np.array([
    [1, 0],
    [-(n2-n1)/r1, 1],
])

T1 = np.array([
    [1, t1/n2],
    [0, 1],
])

R2 = np.array([
    [1, 0],
    [-(n3-n2)/r2, 1],
])

T2 = np.array([
    [1, d/n3],
    [0, 1],
])

R3 = np.array([
    [1, 0],
    [-(n4-n3)/r3, 1],
])

T3 = np.array([
    [1, t2/n4],
    [0, 1],
])

R4 = np.array([
    [1, 0],
    [-(n5-n4)/r4, 1],
])

In [25]:
M = np.dot(T1, R1)
M = np.dot(R2, M)
M = np.dot(T2, M)
M = np.dot(R3, M)
M = np.dot(T3, M)
M = np.dot(R4, M)
M

array([[-5.08266667e-01,  7.48266667e+01],
       [ 2.65333333e-04, -2.00653333e+00]])

In [27]:
M = np.dot(R4, T3)
M = np.dot(M, R3)
M = np.dot(M, T2)
M = np.dot(M, R2)
M = np.dot(M, T1)
M = np.dot(M, R1)
M

array([[-5.08266667e-01,  7.48266667e+01],
       [ 2.65333333e-04, -2.00653333e+00]])

In [29]:
F = 1/2.65333333e-04
F

3768.8442258402565